services:
  comfyui:
    image: snomiao/comfyui
    build: .
    ports:
      - 8188:8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
 