services:
  comfyui:
    image: snomiao/comfyui:cpu
    build: .
    volumes:
      - ./ComfyUI:/ComfyUI
    ports:
      - 8188:8188
# docker run --name comfyui --gpus all -p 8188:8188 snomiao/comfyui:nvidia
# /code/snomiao/ComfyUI-Docker/tree/main/ComfyUI
