services:
  comfyui:
    image: snomiao/comfyui:nvidia
    build: .
    volumes:
      - ../ComfyUI:/ComfyUI
    ports:
      - 8188:8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
